In [1]:
#Dependencies
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from numpy import array
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#Load Data
#VMW = pd.read_csv("VMW.csv")
#VMW = pd.read_csv("VMW2.csv")
#VMW
CSCO = pd.read_csv("CSCO.csv")
CSCO

,Date,Open,High,Low,Close,Adj Close,Volume
0,2017-11-13,33.860001,34.209999,33.830002,33.950001,30.978666,16441500
1,2017-11-14,33.860001,34.160000,33.799999,34.040001,31.060797,17468500
2,2017-11-15,33.970001,34.310001,33.750000,34.110001,31.124666,30829600
3,2017-11-16,36.040001,36.669998,35.830002,35.880001,32.739746,61177100
4,2017-11-17,35.900002,36.320000,35.810001,35.900002,32.758003,27988000
...,...,...,...,...,...,...,...
750,2020-11-05,37.020000,37.299999,36.910000,37.230000,37.230000,23149700
751,2020-11-06,37.560001,37.599998,37.080002,37.529999,37.529999,19475300
752,2020-11-09,39.919998,40.230000,38.119999,38.200001,38.200001,42649500
753,2020-11-10,38.209999,39.029999,38.169998,38.720001,38.720001,31514500
754,2020-11-11,39.009998,39.450001,38.439999,39.330002,39.330002,27332800

In [3]:
del CSCO["Open"]
del CSCO["Close"]
del CSCO["High"]
del CSCO["Low"]
del CSCO["Adj Close"]

In [4]:
CSCO["Next Volume"]=CSCO["Volume"].shift(-1)
CSCO=CSCO.dropna(how='any')
CSCO

           Date    Volume  Next Volume
0    2017-11-13  16441500   17468500.0
1    2017-11-14  17468500   30829600.0
2    2017-11-15  30829600   61177100.0
3    2017-11-16  61177100   27988000.0
4    2017-11-17  27988000   26897800.0
..          ...       ...          ...
749  2020-11-04  30121900   23149700.0
750  2020-11-05  23149700   19475300.0
751  2020-11-06  19475300   42649500.0
752  2020-11-09  42649500   31514500.0
753  2020-11-10  31514500   27332800.0

[754 rows x 3 columns]

In [10]:
#Shape Data
CSCO_vol = CSCO['Volume'].to_numpy()
CSCO_vol = np.float32(CSCO_vol)
X = CSCO_vol.reshape(-1,1)
print("Volume shape")
print(np.shape(X))
CSCO_next = CSCO['Next Volume'].to_numpy()
CSCO_next = np.float32(CSCO_next)
y = CSCO_next.reshape(-1,1)
print("Next Volume shape")
print(np.shape(y))

Volume shape
(754, 1)
Next Volume shape
(754, 1)

In [11]:
X = X.reshape(1,754,1)
y = y.reshape(1,754,1)

In [12]:
#Define Model
model = Sequential()
model.add(LSTM(32))
model.add(Dense(1))
#model.add(Activation('sigmod'))

In [13]:
#Compile model
model.compile(optimizer='sgd', loss='mean_squared_error', metrics=['mean_squared_error'])

In [14]:
#Fit model
#model.fit(X, y, batch_size=10, epoch=100)
model.fit(
    X,
    y,
    batch_size=32,
    epochs=50,
    shuffle=True,
    verbose=2
)

Train on 1 samples
Epoch 1/50
1/1 - 9s - loss: 673163713183744.0000 - mean_squared_error: 673163713183744.0000
Epoch 2/50
1/1 - 2s - loss: 585074336595968.0000 - mean_squared_error: 585074336595968.0000
Epoch 3/50
1/1 - 2s - loss: 511033395380224.0000 - mean_squared_error: 511033395380224.0000
Epoch 4/50
1/1 - 2s - loss: 448800393003008.0000 - mean_squared_error: 448800393003008.0000
Epoch 5/50
1/1 - 2s - loss: 396492422512640.0000 - mean_squared_error: 396492422512640.0000
Epoch 6/50
1/1 - 1s - loss: 352526520025088.0000 - mean_squared_error: 352526520025088.0000
Epoch 7/50
1/1 - 1s - loss: 315572252311552.0000 - mean_squared_error: 315572252311552.0000
Epoch 8/50
1/1 - 1s - loss: 284511451480064.0000 - mean_squared_error: 284511451480064.0000
Epoch 9/50
1/1 - 1s - loss: 258404207558656.0000 - mean_squared_error: 258404207558656.0000
Epoch 10/50
1/1 - 1s - loss: 236460548554752.0000 - mean_squared_error: 236460548554752.0000
Epoch 11/50
1/1 - 2s - loss: 218016314818560.0000 - mean_squared_error: 218016314818560.0000
Epoch 12/50
1/1 - 1s - loss: 202513764581376.0000 - mean_squared_error: 202513764581376.0000
Epoch 13/50
1/1 - 1s - loss: 189483421007872.0000 - mean_squared_error: 189483421007872.0000
Epoch 14/50
1/1 - 1s - loss: 178531220848640.0000 - mean_squared_error: 178531220848640.0000
Epoch 15/50
1/1 - 1s - loss: 169325629538304.0000 - mean_squared_error: 169325629538304.0000
Epoch 16/50
1/1 - 1s - loss: 161588195622912.0000 - mean_squared_error: 161588195622912.0000
Epoch 17/50
1/1 - 1s - loss: 155084642058240.0000 - mean_squared_error: 155084642058240.0000
Epoch 18/50
1/1 - 1s - loss: 149618356649984.0000 - mean_squared_error: 149618356649984.0000
Epoch 19/50
1/1 - 2s - loss: 145023781830656.0000 - mean_squared_error: 145023781830656.0000
Epoch 20/50
1/1 - 2s - loss: 141161951920128.0000 - mean_squared_error: 141161951920128.0000
Epoch 21/50
1/1 - 2s - loss: 137916080717824.0000 - mean_squared_error: 137916080717824.0000
Epoch 22/50
1/1 - 2s - loss: 135187786629120.0000 - mean_squared_error: 135187786629120.0000
Epoch 23/50
1/1 - 2s - loss: 132894592860160.0000 - mean_squared_error: 132894592860160.0000
Epoch 24/50
1/1 - 2s - loss: 130967142400000.0000 - mean_squared_error: 130967142400000.0000
Epoch 25/50
1/1 - 2s - loss: 129347084091392.0000 - mean_squared_error: 129347084091392.0000
Epoch 26/50
1/1 - 2s - loss: 127985386520576.0000 - mean_squared_error: 127985386520576.0000
Epoch 27/50
1/1 - 1s - loss: 126840844845056.0000 - mean_squared_error: 126840844845056.0000
Epoch 28/50
1/1 - 1s - loss: 125878847668224.0000 - mean_squared_error: 125878847668224.0000
Epoch 29/50
1/1 - 1s - loss: 125070269743104.0000 - mean_squared_error: 125070269743104.0000
Epoch 30/50
1/1 - 1s - loss: 124390616334336.0000 - mean_squared_error: 124390616334336.0000
Epoch 31/50
1/1 - 2s - loss: 123819360518144.0000 - mean_squared_error: 123819360518144.0000
Epoch 32/50
1/1 - 1s - loss: 123339238539264.0000 - mean_squared_error: 123339238539264.0000
Epoch 33/50
1/1 - 2s - loss: 122935654219776.0000 - mean_squared_error: 122935654219776.0000
Epoch 34/50
1/1 - 1s - loss: 122596444078080.0000 - mean_squared_error: 122596444078080.0000
Epoch 35/50
1/1 - 1s - loss: 122311348846592.0000 - mean_squared_error: 122311348846592.0000
Epoch 36/50
1/1 - 2s - loss: 122071711481856.0000 - mean_squared_error: 122071711481856.0000
Epoch 37/50
1/1 - 1s - loss: 121870267449344.0000 - mean_squared_error: 121870267449344.0000
Epoch 38/50
1/1 - 1s - loss: 121700960174080.0000 - mean_squared_error: 121700960174080.0000
Epoch 39/50
1/1 - 2s - loss: 121558672605184.0000 - mean_squared_error: 121558672605184.0000
Epoch 40/50
1/1 - 2s - loss: 121439084609536.0000 - mean_squared_error: 121439084609536.0000
Epoch 41/50
1/1 - 1s - loss: 121338547142656.0000 - mean_squared_error: 121338547142656.0000
Epoch 42/50
1/1 - 1s - loss: 121254048694272.0000 - mean_squared_error: 121254048694272.0000
Epoch 43/50
1/1 - 1s - loss: 121183005573120.0000 - mean_squared_error: 121183005573120.0000
Epoch 44/50
1/1 - 1s - loss: 121123337404416.0000 - mean_squared_error: 121123337404416.0000
Epoch 45/50
1/1 - 1s - loss: 121073131585536.0000 - mean_squared_error: 121073131585536.0000
Epoch 46/50
1/1 - 1s - loss: 121030962053120.0000 - mean_squared_error: 121030962053120.0000
Epoch 47/50
1/1 - 1s - loss: 120995520184320.0000 - mean_squared_error: 120995520184320.0000
Epoch 48/50
1/1 - 1s - loss: 120965723848704.0000 - mean_squared_error: 120965723848704.0000
Epoch 49/50
1/1 - 1s - loss: 120940700631040.0000 - mean_squared_error: 120940700631040.0000
Epoch 50/50
1/1 - 1s - loss: 120919620059136.0000 - mean_squared_error: 120919620059136.0000

In [15]:
#Evaluate model
loss, accuracy = model.evaluate(X, y)

1/1 [==============================] - 3s 3s/sample - loss: 120901928484864.0000 - mean_squared_error: 120901928484864.0000

In [16]:
#Make predictions
predictions = model.predict(X)

In [17]:
predictions

array([[23196872.]], dtype=float32)